FROM node:22 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx nx run worker:build
RUN npx nx run worker:prepare-deployment

FROM node:22-slim
WORKDIR /app

COPY --from=builder /app/dist/apps/worker ./dist/apps/worker

EXPOSE 3123
CMD ["node", "dist/apps/worker/main.js"]
